### ISSUE TITLE
Consolidate under src

### ISSUE THREAD

**Issue by asclines** [TTUSDC/cpceed-webapp#13]
As of now, the `src` directory is solely the app source files. I propose we have this folder hierarchy: 
```
src/app
src/api
src/common
```
Where `src/common` can hold all the shared code between API and APP

@NilsG-S Would this be feasible?

**Comment by NilsG-S** [comment]
@asclines 
I see no reason why it shouldn't. The main thing will be changing build paths and the like. I can take care of it in the logger branch I'm working on right now, if you want.

**Comment by ynigoreyes** [comment]
Closing issue as it is irrelevant in new structure
