### ISSUE TITLE
Webpack

### ISSUE THREAD

**Issue by NilsG-S** [TTUSDC/cpceed-webapp#34]
To Do:

- Add compression/minimization/uglification to production builds
- Enhance hot module replacement
  - [React](https://github.com/gaearon/react-hot-loader) - **done**
  - [Redux](https://survivejs.com/webpack/appendices/hmr-with-react/#configuring-hmr-with-redux) - **necessary?**

Done:

**Comment by ynigoreyes** [comment]
We're you able to implement HMR to the point where state of app persists as well?

**Comment by NilsG-S** [comment]
I can't remember, although the issue seems to indicate I have not

**Comment by ynigoreyes** [comment]
Fixed with CRA
