### ISSUE TITLE
Use Polyfills?

### ISSUE THREAD

**Issue by NilsG-S** [TTUSDC/cpceed-webapp#39]
- `history` API
- `fetch` API
...more?

https://stackoverflow.com/questions/43756211/best-way-to-polyfill-es6-features-in-react-app-that-uses-create-react-app
https://hackernoon.com/polyfills-everything-you-ever-wanted-to-know-or-maybe-a-bit-less-7c8de164e423

**Comment by ynigoreyes** [comment]
Fixed with CRA polyfils
