### ISSUE TITLE
Dockerized Test Environment

### ISSUE THREAD

**Issue by NilsG-S** [TTUSDC/cpceed-webapp#59]
I like the idea of Dockerizing our test environment. It eliminates some setup headaches. Plus, the tests will theoretically run the same no matter the development environment. As we start introducing stuff like integration tests, it'll be easy to spin up our entire system.

However, it does introduce some complexity. In particular, managing dependencies. We have two options:

1. Standard docker container. We rebuild the image with each code change. This allows for easy caching of dependency layers. The inconvenience of running two commands can be mitigated by simply having Docker Compose automatically rebuild the image (usually a short process, given the caching).
2. Docker container with volume. Allows for a simpler set of commands. Introduces additional complexity for dependency management. Every time a new package is added, `yarn install` has to be run. In a DockerForWin or DockerForMac context, this can take a long time. It should be alright to just run Yarn on the host, but it's not ideal.

Resources:

- Original conversation: https://github.com/TTUSDC/cpceed-student-app/commit/6ce842273be374c6f7b0f563a8b157ae64e620c8
- Automatic rebuild example: https://github.com/NilsG-S/antifreeze-back-end/blob/master/dev-compose.yml

**Comment by ynigoreyes** [comment]
Okay, so I have a question. Unit testing should not be environment specific (besides node the node version, which we can control). We would test functions. Integration and acceptance testing would depend on the environment, but we would only (properly) test integration through Travis (we could run integration test on local just for funsies, too but eh) Thoughts?

**Comment by NilsG-S** [comment]
So you're proposing that we not Dockerize for unit testing?

**Comment by ynigoreyes** [comment]
Correct. We should not have to dockerize for unit testing for reasons above. As long as we specify our node version, we should be fine. So now we would only build when we push, and keep that off our local Dev machines. 

Unit test should testing everything in isolation anyways

**Comment by NilsG-S** [comment]
You make a good point. I'll remove the unit testing containers before I PR.

I'd argue it's totally possible to properly integration test on a local dev machine using Docker Compose. However, that's for later.
